name: Release

on: [push, create, delete]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: Get Latest Tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
